// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_aXV8mfpzfcmKNHKUurosUwrJAQlm8bY',
    appId: '1:940348571121:web:9d0ab5aeeeb456e140d850',
    messagingSenderId: '940348571121',
    projectId: 'education-app-43e9a',
    authDomain: 'education-app-43e9a.firebaseapp.com',
    storageBucket: 'education-app-43e9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFkY28KQ9kAGtrPl4275Pq6N3c3BKANTY',
    appId: '1:940348571121:ios:3f445b53317cbad540d850',
    messagingSenderId: '940348571121',
    projectId: 'education-app-43e9a',
    storageBucket: 'education-app-43e9a.firebasestorage.app',
    iosClientId: '940348571121-mn1q45rau0p8vq9m7k2iatvmcstcbom1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dnyanzest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFkY28KQ9kAGtrPl4275Pq6N3c3BKANTY',
    appId: '1:940348571121:ios:3f445b53317cbad540d850',
    messagingSenderId: '940348571121',
    projectId: 'education-app-43e9a',
    storageBucket: 'education-app-43e9a.firebasestorage.app',
    iosClientId: '940348571121-mn1q45rau0p8vq9m7k2iatvmcstcbom1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dnyanzest',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWUPSPf9jkkoH6OEj2wtrN2YP6dezwuT8',
    appId: '1:940348571121:android:792281b60273dc8240d850',
    messagingSenderId: '940348571121',
    projectId: 'education-app-43e9a',
    storageBucket: 'education-app-43e9a.firebasestorage.app',
  );

}